version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    env_file:
      - ./.env
    ports:
      - '${PORT}:80'
    volumes:
      - .:/var/www/html
  db:
    image: 'mariadb'
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
